# Site
repository: TaharAmine/TaharAmine.github.io
favicon: images/favicon.ico

# Personal info
name: Tahar Amine ELHOUARI
title: Sr. Penetration Tester & Cyber Security Consultant
email: TaharAmineSec@gmail.com
website: https://medium.com/@MrTaharAmine

# Dark Mode (true/false/never)
darkmode: true

# Social links
twitter_username: MrTaharAmine
#github_username:  TaharAmine
# dribbble_username: jekyll
facebook_username: MrTaharAmine
# flickr_username: jekyll
instagram_username: Mr.Tahar_Amine
linkedin_username: MrTaharAmine
# pinterest_username: jekyll
youtube_username: MrTaharAmineTV
# googleplus_username: +jekyll

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, my name is Tahar Amine and I am a senior penetration tester and cyber security consultant. As well as ethical hacker, I also have multiple years of experience in the information security industry! I have worked at a number of companies in different information technology sectors gaining teamwork and leadership skills and experience. Although some of my qualifications include a  couple of certifications of appreciation from tech giants through my security research, winning of many national and international hacking contests, and detailed & practical knowledge of security & hacking tools, technologies and best practices in both offensive and defensive sides. Well-known bug bounty hunter, who managed to identify and fix security issues concerning worldwide companies and agencies, some of them: Google, EC-Council, Microsoft, Intel, U.S Air Force, U.S Cyber Army, and more.

  I am most skilled in: <mark>Penetration Testing & Vulnerability Assessment (VAPT)</mark> and <mark>Red Teaming</mark>

# Projects Section
projects_title: Projects & Publications

# Experience Section
experience_title: Experience & Background

# Education Section
educaton_title: Education

# More Section
# more_title: A Little More About Me
more_content: | # this will include new lines to allow paragraphs
  Alongside my interests in computer science and ethical hacking, some of my other interests and hobbies are:
   - Business and Entrepreneurship
   - Photography & Photo Editing
   - Military, Army & National Security
   - Learning different stuff & Traveling
   - Sports & Martial Arts
   - Chess & Cars Racing
   - Guns & Knives
#   - [Becoming a ninja](https://www.youtube.com/watch?v=vtg4o__aRMg)

# Footer
footer_show_references: true

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
